config/routes.rb
Rails.application.routes.draw do
  root to: 'plans#index'
  resources :plans
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/elementary_activity.rb
class ElementaryActivity < ActiveHash::Base
  self.data = [
    { id: 0, name: '--', fee: '--' },
    { id: 1, name: '水泳', fee: 120000 },
    { id: 2, name: 'ピアノ', fee: 120000 },
    { id: 3, name: '書道', fee: 120000 },
    { id: 4, name: 'プログラミング', fee: 240000 },
    { id: 5, name: '英会話', fee: 360000 },
  ]
end

app/models/elementary_school.rb
class ElementarySchool < ActiveHash::Base
  self.data = [
    { id: 0, name: '--', fee: '--' },
    { id: 1, name: '公立', fee: 1000000 },
    { id: 2, name: '私立', fee: 3000000 },
  ]
end

app/models/junior_high_activity.rb
class JuniorHighActivity < ActiveHash::Base
  self.data = [
    { id: 0, name: '--', fee: '--' },
    { id: 1, name: '水泳', fee: 240000 },
    { id: 2, name: 'ピアノ', fee: 240000 },
    { id: 3, name: '書道', fee: 240000 },
    { id: 4, name: 'プログラミング', fee: 480000 },
    { id: 5, name: '英会話', fee: 720000 },
  ]
end

app/models/junior_high_school.rb
class JuniorHighSchool < ActiveHash::Base
  self.data = [
    { id: 0, name: '--', fee: '--' },
    { id: 1, name: '公立', fee: 2000000 },
    { id: 2, name: '私立', fee: 6000000 },
  ]
end

app/models/period_six.rb
class PeriodSix < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: 1 },
    { id: 2, name: 2 },
    { id: 3, name: 3 },
    { id: 4, name: 4 },
    { id: 5, name: 5 },
    { id: 6, name: 6 },
  ]
end

app/models/period_three.rb
class PeriodThree < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: 1 },
    { id: 2, name: 2 },
    { id: 3, name: 3 },
  ]
end

app/models/plan.rb
class Plan < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :elementary_school
  belongs_to_active_hash :elementary_activity
  belongs_to_active_hash :period_six
  belongs_to_active_hash :period_three
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plan = Plan.all
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.save
    render :show
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    @plan.update(plan_params)
    render :show 
  end

  def destroy
    plan = Plan.find(params[:id])
    plan.destroy
    redirect_to root_path
  end



  private
  def plan_params
    params.require(:plan).permit(:elementary_school_id, :elementary_activity_id, :period_six_id, :junior_high_school_id, :junior_high_activity_id, :period_three_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JsTest2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/edit.html.erb
<h1>プラン編集</h1>
<h2>プラン<%= @plan.id%></h2>

<div class = 'calculation'>
  <%= form_with(model: @plan, local: true) do |f| %>

    <div class = 'elementary'>
      <h2>小学生</h2>
      <div class = 'elementary_school'>
        <p>・学校（6年）</p>
        <%= f.collection_select(:elementary_school_id, ElementarySchool.all, :id, :name, {}, {class:"hoge", id:"fuga"}) %> 
      </div>
      <div class = 'elementary_activity'>
        <p>・習い事（対象）</p>
        <%= f.collection_select(:elementary_activity_id, ElementaryActivity.all, :id, :name, {}, {class:"hoge", id:"fuga"}) %> 
      </div>
      <div class = 'elementary_activity_period'>
        <p>・習い事（期間）</p>
        <%= f.collection_select(:period_six_id, PeriodSix.all, :id, :name, {}, {class:"hoge", id:"fuga"}) %> 
      </div>
    </div>

    <div class = 'junior_high'>
      <h2>中学生</h2>
      <div class = 'junior_high_school'>
        <p>・学校（３年）</p>
        <%= f.collection_select(:junior_high_school_id, JuniorHighSchool.all, :id, :name, {}, {class:"hoge", id:"fuga"}) %> 
      </div>
      <div class = 'junior_high__activity'>
        <p>・習い事</p>
        <%= f.collection_select(:junior_high_activity_id, JuniorHighActivity.all, :id, :name, {}, {class:"hoge", id:"fuga"}) %> 
      </div>
      <div class = 'junior_high_activity_period'>
        <p>・習い事（期間）</p>
        <%= f.collection_select(:period_three_id, PeriodThree.all, :id, :name, {}, {class:"hoge", id:"fuga"}) %> 
      </div>
    </div>

  <div class = "save">
      <%= f.submit "更新" ,class:"sell-btn" %>
      <%# <%=link_to 'もどる', root_path, class:"back-btn" %>
  </div>



  <% end %>
</div>

app/views/plans/index.html.erb
<p>ようこそ●●さん</p>

<%= link_to 'シミュレーションを始める！', new_plan_path %>

<p>プラン一覧</p>
<% @plan.each do |plan| %>
    <div class="post">
        プラン：<%= link_to plan.id, plan_path(plan.id) %>
    </div>
<% end %>

app/views/plans/new.html.erb
<h1>新規プラン作成</h1>

<div class = 'calculation'>
  <%= form_with(model: @plan, local: true) do |f| %>
    <div class = 'payment'>
        <div class = 'elementary'>
          <h2>小学生</h2>
          <div class = 'elementary_school'>
            <p>・学校（6年）</p>
            <%= f.collection_select(:elementary_school_id, ElementarySchool.all, :id, :name, {}, {class:"hoge", id:"fuga"}) %> 
          </div>
          <div class = 'elementary_activity'>
            <p>・習い事（対象）</p>
            <%= f.collection_select(:elementary_activity_id, ElementaryActivity.all, :id, :name, {}, {class:"hoge", id:"fuga"}) %> 
          </div>
          <div class = 'elementary_activity_period'>
            <p>・習い事（期間）</p>
            <%= f.collection_select(:period_six_id, PeriodSix.all, :id, :name, {}, {class:"hoge", id:"fuga"}) %> 
          </div>
        </div>

        <div class = 'junior_high'>
          <h2>中学生</h2>
          <div class = 'junior_high_school'>
            <p>・学校（３年）</p>
            <%= f.collection_select(:junior_high_school_id, JuniorHighSchool.all, :id, :name, {}, {class:"hoge", id:"fuga"}) %> 
          </div>
          <div class = 'junior_high__activity'>
            <p>・習い事</p>
            <%= f.collection_select(:junior_high_activity_id, JuniorHighActivity.all, :id, :name, {}, {class:"hoge", id:"fuga"}) %> 
          </div>
          <div class = 'junior_high_activity_period'>
            <p>・習い事（期間）</p>
            <%= f.collection_select(:period_three_id, PeriodThree.all, :id, :name, {}, {class:"hoge", id:"fuga"}) %> 
          </div>
        </div>
    </div>

    <div class = 'income'>
    </div>

  <div class = "save">
      <%= f.submit "シミュレーション開始！" ,class:"sell-btn" %>
      <%# <%=link_to 'もどる', root_path, class:"back-btn" %>
  </div>



  <% end %>
</div>

app/views/plans/show.html.erb
<h1>シミュレーション結果</h1>
<h2>プラン<%= @plan.id%></h2>  

<%# 表示箇所検討中 %>
<%= link_to 'トップへ', root_path %>
<%= link_to '編集する', edit_plan_path(@plan.id) %>
<%= link_to '削除する', plan_path(@plan.id), method: :delete %>

<div class="result">
    <table class="aaa">
      <tbody>
        <tr>
          <th class="bbb">小学生：学校</th>
          <td class="ccc" id="bc"><%= ElementarySchool.find(@plan.elementary_school_id).fee %></td>
        </tr>
        <tr>
          <th class="ddd">小学生：習い事</th>
          <td class="eee" id="de"><%= ElementaryActivity.find(@plan.elementary_activity_id).fee %></td>
        </tr>
        <tr>
          <th class="fff">小学生：習い事（期間）</th>
          <td class="ggg" id="fg"><%= PeriodSix.find(@plan.period_six_id).name %></td>
        </tr>
        <tr>
          <th class="hhh">小学生：総合計</th>
          <%# <td class="iii" id="hi">¥<%= ElementaryActivity.find(@plan.elementary_activity_id).fee * PeriodSix.find(@plan.period_six_id).name%></td>
          <td class="iii" id="hi"></td>
        </tr>
      </tbody>
    </table>

    <table class="jjj">
      <tbody>
        <tr>
          <th class="kkk">中学生：学校</th>
          <td class="lll" id="kl"><%= JuniorHighSchool.find(@plan.junior_high_school_id).fee %></td>
        </tr>
        <tr>
          <th class="mmm">中学生：習い事</th>
          <td class="nnn" id="mn"><%= JuniorHighActivity.find(@plan.junior_high_activity_id).fee %></td>
        </tr>
        <tr>
          <th class="ooo">中学生：習い事（期間）</th>
          <td class="ppp" id="op"><%= PeriodThree.find(@plan.period_three_id).name %></td>
        </tr>
        <tr>
          <th class="qqq">中学生：総合計</th>
          <td class="rrr" id="qr"></td>
        </tr>
      </tbody>
    </table>
</div>

    
<canvas id="myBarChart" width="120" height="40"> 
<%# <canvas id="myBarChart" style="position: relative; height:100; width:100"></canvas> %>
  

<table>
<caption>寿司ネタ人気ランキング</caption>
<colgroup span="1" style="width:30px; background-color:#FF9900;">
<colgroup>
<col span="2" style="width:100px; background-color:#FF3300;">
<col span="1" style="width:250px; background-color:#FFCC00;">
</colgroup>
<thead>
<tr><th>順位</th><th>名前</th><th>人気度</th><th>備考</th></tr>
</thead>
<tbody>
<tr><th>１位</th><td>トロ</td><td>☆☆☆☆☆</td><td>やはり何といってもトロ！</td></tr>
<tr><th>２位</th><td>サーモン</td><td>☆☆☆☆</td><td>ほど良い脂の乗りで女性に人気。</td></tr>
<tr><th>３位</th><td>うに</td><td>☆☆☆</td><td>軍艦もので唯一ランクイン。</td></tr>
<tr><th>４位</th><td>えび</td><td>☆☆☆</td><td>プリプリした歯ごたえが魅力。</td></tr>
<tr><th>５位</th><td>イカ</td><td>☆☆</td><td>やはり外せない甘みのあるイカ。</td></tr>
</tbody>
<tfoot>
<tr><td></td><td>※投票対象の寿司ネタは管理者が選定</td><td>※投票ポイントを集計して星（☆）に換算</td><td>※投票者のコメントから抜粋</td></tr>
</tfoot>
</table>


  